# Generated by Django 4.1.7 on 2024-02-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_savedpost_delete_savednews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedpost',
            old_name='news',
            new_name='post',
        ),
    ]
