# Generated by Django 4.1.7 on 2024-02-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_news_savedpost_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendpost',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='sendvideo',
            name='tag',
        ),
        migrations.AddField(
            model_name='sendpost',
            name='tag',
            field=models.ManyToManyField(to='main.tag'),
        ),
        migrations.AddField(
            model_name='sendvideo',
            name='tag',
            field=models.ManyToManyField(to='main.tag'),
        ),
    ]
