# Generated by Django 4.1.7 on 2024-02-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_sendpost_tag_remove_sendvideo_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='ProfileImg'),
        ),
        migrations.AddField(
            model_name='profile',
            name='explanation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='ProfileImg'),
        ),
    ]
